export const FALLBACK_STOCKS = [
  { symbol: "AAPL", name: "Apple Inc.", price: 198.42, change: 2.35, changePercent: 1.2, volume: 52400000, assetClass: "stocks" as const },
  { symbol: "MSFT", name: "Microsoft Corp.", price: 425.18, change: -3.62, changePercent: -0.84, volume: 18300000, assetClass: "stocks" as const },
  { symbol: "GOOGL", name: "Alphabet Inc.", price: 176.34, change: 1.82, changePercent: 1.04, volume: 22100000, assetClass: "stocks" as const },
  { symbol: "AMZN", name: "Amazon.com Inc.", price: 198.71, change: 4.53, changePercent: 2.33, volume: 35800000, assetClass: "stocks" as const },
  { symbol: "TSLA", name: "Tesla Inc.", price: 248.92, change: -12.45, changePercent: -4.76, volume: 98700000, assetClass: "stocks" as const },
  { symbol: "NVDA", name: "NVIDIA Corp.", price: 875.28, change: 18.65, changePercent: 2.18, volume: 45200000, assetClass: "stocks" as const },
  { symbol: "META", name: "Meta Platforms", price: 512.50, change: 3.20, changePercent: 0.63, volume: 15400000, assetClass: "stocks" as const },
  { symbol: "JPM", name: "JPMorgan Chase", price: 198.65, change: -1.10, changePercent: -0.55, volume: 8200000, assetClass: "stocks" as const },
];

export const FALLBACK_CRYPTO = [
  { symbol: "BTC", name: "Bitcoin", price: 67234.50, change: 1230.40, changePercent: 1.86, volume: 28400000000, assetClass: "crypto" as const },
  { symbol: "ETH", name: "Ethereum", price: 3456.78, change: -45.20, changePercent: -1.29, volume: 15600000000, assetClass: "crypto" as const },
  { symbol: "SOL", name: "Solana", price: 148.23, change: 5.67, changePercent: 3.97, volume: 3200000000, assetClass: "crypto" as const },
  { symbol: "XRP", name: "Ripple", price: 0.6234, change: -0.012, changePercent: -1.89, volume: 1800000000, assetClass: "crypto" as const },
  { symbol: "ADA", name: "Cardano", price: 0.4567, change: 0.0123, changePercent: 2.77, volume: 850000000, assetClass: "crypto" as const },
  { symbol: "DOGE", name: "Dogecoin", price: 0.1234, change: 0.0089, changePercent: 7.78, volume: 2100000000, assetClass: "crypto" as const },
];

export const FALLBACK_MEME = [
  { symbol: "PEPE", name: "Pepe", price: 0.0000085, change: 0.0000012, changePercent: 16.44, volume: 580000000, assetClass: "meme_coins" as const },
  { symbol: "WIF", name: "dogwifhat", price: 2.45, change: 0.32, changePercent: 15.02, volume: 420000000, assetClass: "meme_coins" as const },
  { symbol: "BONK", name: "Bonk", price: 0.0000234, change: 0.0000031, changePercent: 15.27, volume: 310000000, assetClass: "meme_coins" as const },
  { symbol: "FLOKI", name: "Floki", price: 0.000185, change: 0.000022, changePercent: 13.50, volume: 280000000, assetClass: "meme_coins" as const },
];

export const FALLBACK_FOREX = [
  { symbol: "EUR/USD", name: "Euro / US Dollar", price: 1.0824, change: -0.0023, changePercent: -0.21, volume: 0, assetClass: "forex" as const },
  { symbol: "GBP/USD", name: "British Pound / USD", price: 1.2845, change: 0.0018, changePercent: 0.14, volume: 0, assetClass: "forex" as const },
  { symbol: "USD/JPY", name: "US Dollar / Japanese Yen", price: 151.34, change: -0.45, changePercent: -0.30, volume: 0, assetClass: "forex" as const },
  { symbol: "USD/CHF", name: "US Dollar / Swiss Franc", price: 0.8976, change: -0.0012, changePercent: -0.13, volume: 0, assetClass: "forex" as const },
  { symbol: "AUD/USD", name: "Australian Dollar / USD", price: 0.6634, change: 0.0035, changePercent: 0.53, volume: 0, assetClass: "forex" as const },
  { symbol: "USD/CAD", name: "US Dollar / Canadian Dollar", price: 1.3654, change: 0.0021, changePercent: 0.15, volume: 0, assetClass: "forex" as const },
];

export const FALLBACK_SP500 = [
  { symbol: "SPY", name: "SPDR S&P 500 ETF", price: 542.18, change: 3.25, changePercent: 0.60, volume: 68200000, assetClass: "sp500" as const },
  { symbol: "IVV", name: "iShares Core S&P 500 ETF", price: 545.65, change: 2.98, changePercent: 0.55, volume: 5200000, assetClass: "sp500" as const },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF", price: 478.32, change: 2.65, changePercent: 0.56, volume: 4100000, assetClass: "sp500" as const },
  { symbol: "QQQ", name: "Invesco QQQ Trust", price: 445.80, change: 5.42, changePercent: 1.23, volume: 32400000, assetClass: "sp500" as const },
  { symbol: "DIA", name: "SPDR Dow Jones ETF", price: 392.15, change: 1.85, changePercent: 0.47, volume: 3100000, assetClass: "sp500" as const },
];

export const FALLBACK_COMMODITIES = [
  { symbol: "GC=F", name: "Gold Futures", price: 2345.60, change: 18.40, changePercent: 0.79, volume: 215000, assetClass: "commodities" as const },
  { symbol: "SI=F", name: "Silver Futures", price: 29.85, change: 0.42, changePercent: 1.43, volume: 58000, assetClass: "commodities" as const },
  { symbol: "CL=F", name: "Crude Oil WTI", price: 78.34, change: -1.25, changePercent: -1.57, volume: 345000, assetClass: "commodities" as const },
  { symbol: "NG=F", name: "Natural Gas", price: 2.65, change: 0.08, changePercent: 3.11, volume: 182000, assetClass: "commodities" as const },
  { symbol: "HG=F", name: "Copper Futures", price: 4.52, change: 0.06, changePercent: 1.35, volume: 42000, assetClass: "commodities" as const },
];

export const FALLBACK_NEWS = [
  {
    id: "n1",
    title: "Fed Holds Rates Steady, Signals Two Cuts Later This Year",
    description: "The Federal Reserve maintained its benchmark interest rate at 5.25-5.50%, while indicating two potential rate cuts in the second half of the year.",
    url: "#",
    source: "Financial Times",
    publishedAt: new Date().toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["SPY", "QQQ", "TLT"],
  },
  {
    id: "n2",
    title: "Bitcoin Surges Past $67,000 as ETF Inflows Hit Record",
    description: "Bitcoin surged past $67,000 as spot Bitcoin ETF inflows reached a new single-day record of $1.2 billion.",
    url: "#",
    source: "CoinDesk",
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["BTC", "ETH"],
  },
  {
    id: "n3",
    title: "NVIDIA Unveils Next-Gen AI Chip, Stock Rises 4%",
    description: "NVIDIA announced its next-generation Blackwell Ultra GPU, claiming a 40% performance improvement over previous generation.",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["NVDA", "AMD", "INTC"],
  },
  {
    id: "n4",
    title: "Oil Prices Drop 3% on OPEC+ Production Increase Concerns",
    description: "Oil prices fell sharply amid reports that OPEC+ may begin unwinding production cuts sooner than anticipated.",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["XOM", "CVX", "USO"],
  },
  {
    id: "n5",
    title: "Apple Reports Record Services Revenue in Q2 Earnings",
    description: "Apple's services segment hit an all-time high of $24.1 billion, offsetting a slight decline in iPhone sales.",
    url: "#",
    source: "CNBC",
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["AAPL"],
  },
  {
    id: "n6",
    title: "Ethereum Layer-2 Transaction Volume Surpasses Mainnet",
    description: "For the first time, Ethereum layer-2 networks processed more daily transactions than the Ethereum mainnet, marking a milestone for scaling solutions.",
    url: "#",
    source: "The Block",
    publishedAt: new Date(Date.now() - 18000000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["ETH", "ARB", "OP"],
  },
  {
    id: "n7",
    title: "US GDP Growth Revised Up to 3.4% in Q4, Beating Expectations",
    description: "The Bureau of Economic Analysis revised Q4 GDP growth up to 3.4%, exceeding the 3.2% preliminary estimate on stronger consumer spending.",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 21600000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["SPY", "DIA"],
  },
  {
    id: "n8",
    title: "Jobless Claims Fall to 212,000, Labor Market Remains Tight",
    description: "Initial jobless claims dropped to 212,000, below the consensus estimate of 218,000, signaling continued strength in the labor market.",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 25200000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["SPY"],
  },
  {
    id: "n9",
    title: "Microsoft Partners with OpenAI on $100B Data Center Project",
    description: "Microsoft and OpenAI are jointly planning a $100 billion data center project named 'Stargate' to power next-generation AI workloads.",
    url: "#",
    source: "The Verge",
    publishedAt: new Date(Date.now() - 28800000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["MSFT"],
  },
  {
    id: "n10",
    title: "Tesla Deliveries Beat Estimates, Stock Rides Momentum",
    description: "Tesla reported quarterly deliveries of 443,000 vehicles, surpassing analyst estimates of 430,000 and driving a pre-market rally.",
    url: "#",
    source: "CNBC",
    publishedAt: new Date(Date.now() - 32400000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["TSLA"],
  },
  {
    id: "n11",
    title: "Solana DeFi TVL Surges Past $5 Billion, Marking New High",
    description: "Solana's total value locked in DeFi protocols has surpassed $5 billion for the first time, driven by liquid staking and DEX activity.",
    url: "#",
    source: "The Block",
    publishedAt: new Date(Date.now() - 36000000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["SOL"],
  },
  {
    id: "n12",
    title: "EUR/USD Tests Key Support at 1.0750 as ECB Holds Rates",
    description: "The euro weakened against the dollar as the European Central Bank held rates steady while signaling a potential cut in June.",
    url: "#",
    source: "Financial Times",
    publishedAt: new Date(Date.now() - 39600000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["EUR/USD"],
  },
  {
    id: "n13",
    title: "JPMorgan Q1 Profit Rises 8% on Higher Interest Income",
    description: "JPMorgan Chase reported an 8% increase in Q1 profit, driven by higher net interest income and strong performance in investment banking.",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 43200000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["JPM"],
  },
  {
    id: "n14",
    title: "Gold Hits New All-Time High Above $2,400 Per Ounce",
    description: "Gold prices reached a new record high above $2,400 per ounce as geopolitical tensions and rate cut expectations fuel safe-haven demand.",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 46800000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["GC=F", "GLD"],
  },
  {
    id: "n15",
    title: "US Inflation Data Comes in Hot, Treasury Yields Spike",
    description: "March CPI rose 3.5% year-over-year, above the 3.4% expected, causing a sharp sell-off in bonds and a spike in Treasury yields.",
    url: "#",
    source: "CNBC",
    publishedAt: new Date(Date.now() - 50400000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["TLT", "SPY", "QQQ"],
  },
  {
    id: "n16",
    title: "Amazon Announces $15B Stock Buyback Program",
    description: "Amazon's board authorized a new $15 billion share repurchase program, signaling confidence in the company's long-term growth trajectory.",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 54000000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["AMZN"],
  },
  {
    id: "n17",
    title: "XRP Rallies 12% on Positive SEC Settlement Speculation",
    description: "Ripple's XRP surged 12% amid growing speculation that the SEC lawsuit may be nearing a favorable resolution for the company.",
    url: "#",
    source: "CoinDesk",
    publishedAt: new Date(Date.now() - 57600000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["XRP"],
  },
  {
    id: "n18",
    title: "UK Inflation Falls to 3.2%, BoE Rate Cut Prospects Rise",
    description: "UK CPI inflation fell to 3.2% in March, its lowest level in over two years, increasing the likelihood of a Bank of England rate cut.",
    url: "#",
    source: "Financial Times",
    publishedAt: new Date(Date.now() - 61200000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["GBP/USD"],
  },
  {
    id: "n19",
    title: "Meta Launches Open-Source AI Model, Shares Climb",
    description: "Meta released its latest open-source large language model, positioning itself as a leader in the democratization of AI technology.",
    url: "#",
    source: "CNBC",
    publishedAt: new Date(Date.now() - 64800000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["META"],
  },
  {
    id: "n20",
    title: "Crude Oil Inventory Build Exceeds Expectations, Prices Dip",
    description: "EIA reported a crude oil inventory build of 5.8 million barrels, well above the expected 1.2 million, sending oil prices lower.",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 68400000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["CL=F", "USO"],
  },
  {
    id: "n21",
    title: "Federal Reserve Minutes Reveal Concerns Over Sticky Inflation",
    description: "The Fed's March meeting minutes showed officials remain cautious about inflation persistence, with several members advocating patience on rate cuts.",
    url: "#",
    source: "Financial Times",
    publishedAt: new Date(Date.now() - 72000000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["SPY", "TLT"],
  },
  {
    id: "n22",
    title: "Apple Vision Pro Sales Miss Targets by 40%",
    description: "Apple has sold approximately 380,000 Vision Pro units since launch, well below the 600,000 target, as high pricing limits consumer adoption.",
    url: "#",
    source: "CNBC",
    publishedAt: new Date(Date.now() - 75600000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["AAPL"],
  },
  {
    id: "n23",
    title: "Japan Yen Intervention Fears Grow as USD/JPY Tests 155",
    description: "The yen weakened past 154 against the dollar, prompting fresh warnings from Japanese officials about potential intervention in currency markets.",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 79200000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["USD/JPY"],
  },
  {
    id: "n24",
    title: "Cardano Network Activity Hits Record High on DeFi Growth",
    description: "Cardano's daily active addresses reached an all-time high as DeFi protocols on the network surpassed $500 million in total value locked.",
    url: "#",
    source: "The Block",
    publishedAt: new Date(Date.now() - 82800000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["ADA"],
  },
  {
    id: "n25",
    title: "Nike Stock Falls as Revenue Guidance Disappoints",
    description: "Nike shares dropped 5% after the company issued weaker-than-expected revenue guidance, citing cautious consumer spending in North America.",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["NKE"],
  },
  {
    id: "n26",
    title: "China Industrial Production Misses Forecasts, Copper Drops",
    description: "China's industrial production grew 5.1% year-over-year in March, below the 5.5% expected, weighing on industrial metals and copper prices.",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 90000000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["HG=F", "FCX"],
  },
  {
    id: "n27",
    title: "Dogecoin Surges 15% After Twitter Payments Integration Hint",
    description: "Dogecoin jumped 15% following speculation that X (formerly Twitter) may integrate DOGE payments through their upcoming financial platform.",
    url: "#",
    source: "CoinDesk",
    publishedAt: new Date(Date.now() - 93600000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["DOGE"],
  },
  {
    id: "n28",
    title: "US Housing Starts Fall to 1.34 Million, Building Permits Slip",
    description: "Housing starts declined to a seasonally adjusted annual rate of 1.34 million, below the 1.42 million consensus, as high mortgage rates bite.",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 97200000).toISOString(),
    sentiment: "negative" as const,
    relatedSymbols: ["XHB"],
  },
  {
    id: "n29",
    title: "Microsoft Reports Azure Revenue Growth Accelerating to 31%",
    description: "Microsoft's Azure cloud revenue grew 31% year-over-year, accelerating from the previous quarter and exceeding analyst expectations of 28%.",
    url: "#",
    source: "CNBC",
    publishedAt: new Date(Date.now() - 100800000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["MSFT"],
  },
  {
    id: "n30",
    title: "Swiss National Bank Cuts Rate by 25bps, Shocks Markets",
    description: "The Swiss National Bank unexpectedly cut its policy rate by 25 basis points to 1.25%, becoming the first major central bank to ease policy.",
    url: "#",
    source: "Financial Times",
    publishedAt: new Date(Date.now() - 104400000).toISOString(),
    sentiment: "positive" as const,
    relatedSymbols: ["USD/CHF", "EUR/USD"],
  },
];

export const FALLBACK_DISCLAIMER = "Informational only. Not investment advice.";